version: "3"
services:   
  appA:
    image: "appa:latest"
    environment:
        - ConnectionStrings:DefaultConnection=Host=db;Database=postgres;Username=postgres;Password=docker
        - AppBSettings:CarsUrl=http://appB:80/api/cars
    ports:
      - 10000:80
    depends_on:
      - db
  appB:
    image: "appb:latest"
    environment:
        - ConnectionStrings:DefaultConnection=Host=db;Database=postgres;Username=postgres;Password=docker
        - AppASettings:FilmsUrl=http://appA:80/api/films
    ports:
      - 10001:80
    depends_on:
      - db      
  db:
    image: postgres
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=docker
        - POSTGRES_DB=postgres
    ports:
        - "5432:5432"
    volumes:
        - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh